version: '3.9'

services:

  app:
    container_name: app-front
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  api:
    container_name: app-api
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - ./backend:/app
    expose:
      - 4000
    ports:    
      - 4000:4000
    depends_on:
      - db
    command: bash -c 'yarn migration:run && yarn dev'
  
  db:
    container_name: app-db
    image: postgres:14.3
    expose:
      - 5432
    ports:
      - 5431:5432
    env_file:
      - ./backend/.env